### ISSUE TITLE
Why? What? Who? How?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-nerves#1]
# Why?

In the past we have used Python or Node.js to build IoT/Robotics projects but it can be tedious to test and deploy them.
Nerves https://www.nerves-project.org simplifies building, deploying, and securely managing a fleet of IoT devices.
![image](https://user-images.githubusercontent.com/194400/86004253-f1f49a00-ba0a-11ea-8bdf-74e7b939fd17.png)

# What?

Nerves lets us tap into the Elixir/Erlang build+deploy system for much simpler management of IoT projects.
[`Elixir`](https://github.com/dwyl/learn-elixir/issues/102) is ideally suited for event driven IoT. Elixir code ends up being a _lot_ simpler than the equivalent `JavaScript` and easier to secure than `Python`. 

# Who?

This introductory tutorial is aimed at anyone who is interested in building their _first_ project using Nerves.
It takes you from complete beginner - never having done any IoT - to first _fully_ functional Nerves IoT project.

# How?

Using the getting started guide https://hexdocs.pm/nerves/getting-started.html as a starting point,
assume the person is starting out with a known state:

+ Basic knowledge of Elixir Sytnax
+ Known target device: Raspberry Pi Zero W *or* Raspberry Pi 3/4
+ 30-60 mins of time.

# Todo

+ [x] Create a complete beginner's tutorial that a noob can follow.
  > Please follow the format of https://github.com/dwyl/phoenix-todo-list-tutorial or https://github.com/dwyl/phoenix-chat-example and include as much detail as you can to minimise the chance of the person getting stuck.
+ [x] It's safe to _assume_ they have basic Elixir Syntax knowledge.
+ [x] Assume they have a Raspberry Pi Zero W *or* Raspberry Pi 3/4 
> Provide links to buy the required components if the reader does not already have them.
+ [x] Hook an LED up to the PI and make it blink using Elixir + Nerves
+ [x] If you can think of a more advanced example, go for it!

@th0mas the order with your NFC reader https://github.com/dwyl/smart-home-security-system/issues/1#issuecomment-651007039 
and Raspberry Pi 4 starter kit was placed today:

![image](https://user-images.githubusercontent.com/194400/86007282-13f01b80-ba0f-11ea-8d38-6014502deef5.png)

While you are waiting for delivery, would mind taking a look at this issue? 
It would be _really_ good for us to have a beginner-friendly Nerves + RPi + "Blinky Light" tutorial.
Feel free to make it as basic or as interesting as you like! 
You've already don't the "_hard_" part in your project https://github.com/th0mas/Fancy-Lights
We just need the _steps_ you took to get to your end result (_minus the IKEA light, just a basic LED is enough_).

Please create a new branch and Pull Request in this Repo. 🆕 
Assign to me once you feel it's ready to be reviewed. 👀 
P.S. I know this is not as _exciting_ as hacking on the code for the Auth/Security, but it's a necessary building block to ensure that _other_ people in the team can follow along with the code we end up writing for the Smart Home. 💡 🏡  

When you assign the PR to me I will attempt to follow it from scratch with the kit sitting on my desk. 😉 
![raspberry-pi-starter-kit-on-desk](https://user-images.githubusercontent.com/194400/86009402-1607a980-ba12-11ea-9238-05c4a5199c85.jpeg)

**Comment by t0mhaines** [comment]
@nelsonic can we consider this issue closed now?

**Comment by nelsonic** [comment]
@th0mas yeah, the `README.md` and sample project are looking good. 👀 👍 
We might extend them later in response to reader feedback, but for now, yes, let's close this issue. ✅ 
Thanks again! 🙌
